version: "3"

services:
  orbis_db:
    container_name: orbis_db
    image: orbis_db
    build:
      context: orbis_db
    expose:
      - 5432
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  orbis_geoserver:
    container_name: orbis_geoserver
    image: orbis_geoserver
    build:
      context: orbis_geoserver
    depends_on:
      - orbis_db
    environment:
      DBHOST: orbis_db
    expose:
      - 8080
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"
    command: >
      /bin/sh -c "
        while ! nc -z orbis_db 5432;
        do
          echo 'Waiting for postgres...';
          sleep 5;
        done;
        /usr/local/tomcat/bin/catalina.sh run;
      "

  orbis_app:
    container_name: orbis_app
    image: orbis_app
    build:
      context: orbis_app
    volumes:
      - webroot:/var/www/html
    depends_on:
      - orbis_db
    environment:
      DBHOST: orbis_db
    expose:
      - 9000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

  orbis_webserver:
    container_name: orbis_webserver
    image: nginx:alpine
    volumes:
      - webroot:/var/www/html
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"

volumes:
     webroot:
